### ISSUE TITLE
Whitespace SCSS issues are unnecessarily breaking the build

### ISSUE THREAD

**Issue by davidpanik** [realise-labs/gulp-boilerplate#18]
stylelint is reporting issues like this:

76:1    ⚠  Unexpected whitespace at end of line (no-eol-whitespace) [stylelint]

Which is fine as a warning, but postcss-reporter is then erroring as a result and preventing new CSS from being generated.

This is very annoying.

[11:47:02] Starting 'scss-lint'...

src/styles/common/_typography.scss
76:1    ⚠  Unexpected whitespace at end of line (no-eol-whitespace) [stylelint]

[11:47:02] 'scss-lint' errored after 107 ms
[11:47:02] Error in plugin 'gulp-postcss'
Message:

** postcss-reporter: warnings or errors were found **
Details:
    fileName: C:\Work in Progress\Architas\src\styles\common\_typography.scss
Stack:
Error:
** postcss-reporter: warnings or errors were found **
    at C:\XXXXX\node_modules\postcss-reporter\lib\reporter.js:69:13
    at LazyResult.run (C:\XXXXX\node_modules\postcss\lib\lazy-result.js:270:20)
    at LazyResult.asyncTick (C:\XXXXX\node_modules\postcss\lib\lazy-result.js:185:32)
    at C:\XXXXX\node_modules\postcss\lib\lazy-result.js:190:27

**Comment by davidpanik** [comment]
I've fixed this by changing the "throwError" setting from true to false.

@jameshaddrill You may still want to review the underlying linting rules though.
